modLoader="javafml"
loaderVersion="[64,)"
license="MIT"

[[mods]]
    modId="gouge"
    version="${file.jarVersion}"
    displayName="Gouge"
    description="Slam your pickaxe into a wall to save yourself from a fatal fall."
    authors="Simplezes"
    logoFile="icon.png"

[[dependencies.gouge]]
    modId="forge"
    mandatory=true
    versionRange="[64,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gouge]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,26.3)"
    ordering="NONE"
    side="BOTH"
