plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-tag-api-v1"
    }

    implementation "com.electronwill.night-config:toml:3.8.1"
    include "com.electronwill.night-config:toml:3.8.1"
    include "com.electronwill.night-config:core:3.8.1"
}

sourceSets.main.java.srcDir file("../common/src/main/java")
sourceSets.main.resources.srcDir file("../common/src/main/resources")

loom {
    mixin {
        defaultRefmapName = "gouge.refmap.json"
    }
    runs {
        client {
            client()
            configName = "Host"
            runDir = "run"
            programArgs "--username", "Host"
        }
        client2 {
            client()
            configName = "Guest"
            runDir = "run2"
            programArgs "--username", "Guest"
        }
        server {
            server()
            configName = "DedicatedServer"
            runDir = "runserver"
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
