plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

version = mod_version
group = maven_group
base.archivesName = archives_base_name

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets.main.output.resourcesDir = sourceSets.main.output.classesDirs.singleFile

sourceSets.main.java.srcDir file("../common/src/main/java")
sourceSets.main.resources.srcDir file("../common/src/main/resources")

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            args "--mixin.config=gouge.mixins.json"
        }
        client { mods { gouge { source sourceSets.main } } }
        server { mods { gouge { source sourceSets.main } } }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    compileOnly "com.electronwill.night-config:toml:3.8.1"
    compileOnly "com.electronwill.night-config:core:3.8.1"
}

jar {
    manifest {
        attributes([
            'MixinConfigs': 'gouge.mixins.json',
            'Implementation-Version': project.version
        ])
    }
}
