plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

version = mod_version
group = maven_group
base.archivesName = archives_base_name

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets.main.output.resourcesDir = sourceSets.main.output.classesDirs.singleFile

minecraft {
    mappings channel: 'official', version: minecraft_version
    runs {
        client {
            workingDirectory project.file('run')
            mods { gouge { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run')
            mods { gouge { source sourceSets.main } }
        }
    }
}

mixin {
    add sourceSets.main, 'gouge.refmap.json'
    config 'gouge.mixins.json'
}

reobf {
    jar {}
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
    manifest {
        attributes([
            'MixinConfigs': 'gouge.mixins.json',
            'Implementation-Version': project.version
        ])
    }
    finalizedBy 'reobfJar'
}
