modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
    modId="gouge"
    version="${file.jarVersion}"
    displayName="Gouge"
    description="Slam your pickaxe into a wall to save yourself from a fatal fall."
    authors="Simplezes"
    logoFile="icon.png"

[[dependencies.gouge]]
    modId="neoforge"
    type="required"
    versionRange="[26.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gouge]]
    modId="minecraft"
    type="required"
    versionRange="[26.1,26.3)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="gouge.mixins.json"
