plugins {
    id 'java'
    id 'net.neoforged.moddev.legacyforge' version '2.0.143'
}

version = mod_version
group = maven_group
base.archivesName = archives_base_name

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets {
    common {
        java.srcDirs = [file("../common/src/main/java")]
        resources.srcDirs = [file("../common/src/main/resources")]
    }
    main {
        compileClasspath += common.output
        runtimeClasspath += common.output
    }
}

repositories {
    mavenCentral()
}

legacyForge {
    enable {
        neoForgeVersion = neo_version
    }

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        gouge {
            sourceSet sourceSets.main
            sourceSet sourceSets.common
        }
    }
}

dependencies {
    compileOnly "com.electronwill.night-config:toml:3.6.4"
    compileOnly "com.electronwill.night-config:core:3.6.4"
    commonAnnotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    commonCompileOnly "com.electronwill.night-config:toml:3.6.4"
    commonCompileOnly "com.electronwill.night-config:core:3.6.4"
}

configurations.commonCompileOnly.extendsFrom(configurations.modDevCompileDependencies)

mixin {
    add sourceSets.common, 'gouge.refmap.json'
    config 'gouge.mixins.json'
}

jar {
    from sourceSets.common.output
    from(layout.buildDirectory.file('mixin/gouge.refmap.json'))
    manifest {
        attributes([
            'MixinConfigs': 'gouge.mixins.json',
            'Implementation-Version': project.version
        ])
    }
}
