plugins {
    id 'java'
    id 'net.neoforged.moddev.legacyforge' version '2.0.143'
}

version = mod_version
group = maven_group
base.archivesName = archives_base_name

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    enable {
        neoForgeVersion = neo_version
    }

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        gouge {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, 'gouge.refmap.json'
    config 'gouge.mixins.json'
}

jar {
    manifest {
        attributes([
            'MixinConfigs': 'gouge.mixins.json',
            'Implementation-Version': project.version
        ])
    }
}
